window.APP_CONFIG = Object.freeze({
  LIFF_ID: 'PUT_YOUR_LIFF_ID_HERE',
  GAS_WEB_APP_URL: 'PUT_YOUR_APPS_SCRIPT_WEB_APP_EXEC_URL_HERE',
  DEPARTMENT: 'วิศวกรรมผลิต 1',
  APP_NAME: 'Leave Management',
  MOBILE_ONLY: true,
  REQUIRE_GROUP_CONTEXT: true,
  DEFAULT_DASHBOARD_MODE: 'DAILY',
  DEFAULT_HOURS_PER_DAY: 8,
  REQUEST_TIMEOUT_MS: 25000
});
